
services:
  
  #database containers
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 8001:80
    volumes: 
      - mysql-vol:/var/lib/mysql
    env_file:
      - .env
    networks: 
    - database
    
  databackend:
    build: ./databackend
    container_name: databackend
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - database


  #frontend containers
  frontend:
    container_name: frontend-react
    image: frontend-image
    build:
      context: ./frontend/
    networks:
      - frontend
    ports:
      - 8004:80

  #backend containers
  backend:
    build: ./backend
    container_name: backend-image
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    networks:
      - backend

  #rabbitmq container
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

volumes:
  mysql-vol:



networks:
  database:
  frontend:
  backend:
