
services:

  #rabbitmq container
  rabbitmq:
    image: rabbitmq:3-management 
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rmq-vol:/var/lib/rabbitmq
    networks:
      - database
      - frontend
      - backend

  #database containers
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 8001:8001
      - 3306:3306
    expose:
      - 8001
      - 3306
    volumes: 
      - mysql-vol:/var/lib/mysql
    env_file:
      - .env
    networks: 
    - database

    
  databackend:
    image: databackend
    build: 
      context: ./databackend/
    container_name: databackend
    restart: always
    ports:
      - 8000:8000
      - 3306
    expose:
      - 8002
      - 3306
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - database


  #frontend containers
  frontend:
    container_name: frontend-react
    image: frontend-image
    build:
      context: ./frontend/
    networks:
      - frontend
    ports:
      - 8004:80

  #backend containers
  backend:
    image: backend
    build: 
      context: ./backend/
    container_name: backend-image
    restart: always
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    networks:
      - backend



volumes:
  mysql-vol:
    name: mysql-vol
  rmq-vol:
    name: rmq-vol



networks:
  database:
    name: database
  frontend: 
    name: frontend
  backend: 
    name: backend
